### Crop Face from user

In [1]:
# import libraries
import os
import cv2
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
from config import Path


In [18]:
def face_detect(img):
    img=np.array(img,dtype="uint8")
    img=cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    haar_cascade=cv2.CascadeClassifier(Path["haar_face"])
    faces_rect=haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=3)
    return faces_rect

In [13]:
Dir=Path["image"]
users=os.listdir(Dir)
print(f"[INFO] Find {len(users)} users")
color=[0, 255, 0]
threshold=15000

for user in users:
    images=os.listdir(os.path.join(Dir, user))
    print(f"[INFO] Start processing {user}")
    # os.mkdir(os.path.join(Path["face"], user))

    num=0

    for last_name in images:
        img_name=f"{user}_{num}.{last_name.split('.')[-1]}"
        # print(f"[INFO] Start processing {img_name}")
        img_path=os.path.join(Dir, user, img_name)
        if last_name!=img_name:
            os.rename(os.path.join(Dir, user, last_name), img_path)

        img=cv2.imread(img_path)
        faces_rect=face_detect(img)
        # print(f"[INFO] Find {len(faces_rect)} faces")
        
        if len(faces_rect)>0:
            for (x, y, w, h) in faces_rect: 
                if w*h>=threshold:
                    # print((x, y, w, h),(w*h), num, "\n")
                    # img=cv2.cvtColor(img, cv2.COLOR_)
                    crop=img[y:y+h, x:x+w]
                    cv2.imwrite(os.path.join(Path["face"], user, f"crop_{img_name}_{num}.png"), crop)
                    # img=cv2.rectangle(img, (x, y), (x+w, y+h), color, 30)
                    # cv2.imwrite(os.path.join(Path["result"], f"{last_name}_{num}.jpg"), img)

        num+=1

print("[INFO] Processing sucsefully end")


[INFO] Find 12 users
[INFO] Start processing Anastasia_Kalinkina
[INFO] Start processing Anastasia_Khudyakova
[INFO] Start processing Denis_Cherepanov
[INFO] Start processing Makar_Averkin
[INFO] Start processing Matvey_Panteleev
[INFO] Start processing Maxim_Zamyatin
[INFO] Start processing Mikhail_Kobozev
[INFO] Start processing Nikita_Kholodarev
[INFO] Start processing Pashnin_Leonid
[INFO] Start processing Pyatkin_MI
[INFO] Start processing Sergey_Klinyushin
[INFO] Start processing Varvara_Moravskaya
[INFO] Processing sucsefully end


In [22]:
img_path=os.path.join(Path["image"], "Denis_Cherepanov", "Denis_Cherepanov_0.jpg")
image=cv2.imread(img_path)
print(face_detect(image))
num=0
for (x, y, w, h) in faces_rect:
    image=cv2.rectangle(image, (x, y), (x+w, y+h), color, 30)
    cv2.imwrite(os.path.join(Path["result"], f"Denis_Cherepanov_{num}.jpg"), image)
    num+=1

[[1344  706   26   26]
 [3440 1626  801  801]
 [1244 2688 2022 2022]
 [ 482 1963  182  182]
 [3472 1903  200  200]
 [4028 1990   52   52]
 [ 224 2327   73   73]]
